### ISSUE TITLE
Always stay consistent with code formatting. 

### ISSUE THREAD

**Issue by josephtkim** [Freddie1234/prj-rev-bwfs-tea-cozy#3]
In any code you write, it is always important to stay consistent with the formatting, which should try to follow best guidelines. For the HTML code, it is best practice to indent elements that are nested by 1 indent relative to the parent element always. Here's how the formatting should look for some sections of your code,

```html
  <body>
    <div id="Mission"></div>
      <div class="Missiontitle">
        <h2>Our Mission</h2>
        <h4>Handpicked, Artisanally Curated, Free Range, Sustainable, Small Batch, Fair Trade, Organic Tea</h4>
      </div>
      <div class="Month">
        <div id="Featured Tea"></div>
          <h3>Tea of the Month</h3>
          <h4>What's Steeping at The Tea Cozy?</h4>
          <div class="Images1">
            <ul>
              <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-berryblitz.jpg">
              <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-spiced-rum.jpg">
              <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-donut.jpg">
            </ul>
          </div>
```

You should also apply this to your CSS, where each property is indented inside the selectors, and each selector is separated by an empty space. Here is how the code should look

```css
html {
  background-color: black;
  font-size: 22px;
  color: white;
  font-family: Helvetica;
  opacity: 0.9;
}

body {
  margin: 0;
  padding: 0px;
}

img {
  height: auto;
  width: auto;
}
```
